networks:
  app-net-ecommerce-api:


services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ecommerce_api # Type image's name
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.aspnet/https:/https:ro
    env_file:
      - .env
    networks:
      - app-net-ecommerce-api
