name: Deploy frontedn to GH Pages

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Build and test ecommerce-web-app"]
    types:
      - completed

env:
  NODE_VERSION: '22.x'
  WORKING_DIRECTORY: src/ecommerce-web-app

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    environment:
      name: staging
      url: ${{ format('https://{0}.github.io/{1}', github.repository_owner, github.event.repository.name) }}

    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }} 
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }} 
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }} 

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: npm ci, build and test
        run: |
          npm ci
          npm run build

      - name: Extract commit message
        id: extract_message
        run: |
          COMMIT_MESSAGE=$(jq -r '.head_commit.message' $GITHUB_EVENT_PATH)
          echo "Commit message is: $COMMIT_MESSAGE"
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          full_commit_message: $COMMIT_MESSAGE
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.WORKING_DIRECTORY }}/build
