name: Rebase Main into dependencies-updating

on:
  push:
    branches:
      - main

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
  TARGET_BRANCH: dependencies-updating

jobs:
  rebase-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          ref: ${{ env.TARGET_BRANCH }}
          fetch-depth: 0

      - name: Perform rebase
        run: |
          git config --global user.name "leonardoalvarez20"
          git config --global user.email "117400391+leonardoalvarez20@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.CI_GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull
          git checkout "$DEFAULT_BRANCH"
          git checkout "$TARGET_BRANCH"
          git rebase "$DEFAULT_BRANCH"
          git push
